sudo: required
services:
  - docker


before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y qemu-kvm libvirt-bin seabios
  - wget http://iso.reactos.org/regtestcd/bootcdregtest-70637.iso -O /tmp/bootcdregtest-70637.iso

language: c

compiler:
  - gcc

script:
  - qemu-img create /tmp/ReactOS.img 2000M
  - qemu-system-i386 -m 512 -cdrom /tmp/bootcdregtest-70637.iso -hda /tmp/ReactOS.img -boot d -localtime -serial stdio -vga std -vnc :0
