sudo: required

#services:
#  - docker


before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y qemu-kvm libvirt-bin libvirt-dev seabios virtinst virt-viewer
  - wget http://iso.reactos.org/regtestcd/bootcdregtest-70637.iso -O /tmp/bootcdregtest-70637.iso

language: c

compiler:
  - gcc

script:
  - git clone --depth=50 --branch=master https://github.com/AmineKhaldi/TestingTravis.git /tmp/TestingTravis
  - qemu-img create /opt/buildbot/kvmtest/ros.img 2000M
  - sudo virt-install -n ReactOS --disk path=/opt/buildbot/kvmtest/ros.img --ram=512 --os-type=linux --graphics vnc,listen=0.0.0.0 --network bridge=virbr0 --cdrom=/tmp/bootcdregtest-70637.iso --boot cdrom
  - svn checkout svn://svn.reactos.org/project-tools/trunk/sysreg2 /tmp/sysreg2
  - cd /tmp/sysreg2 && make
  - sudo /tmp/sysreg2/sysreg2 /tmp/TestingTravis/sysreg.xml
  #- qemu-system-i386 -m 512 -cdrom /tmp/bootcdregtest-70637.iso -hda /tmp/ReactOS.img -boot d -localtime -serial stdio -vga std -vnc :0
