sudo: required
services:
  - docker


before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y qemu-kvm libvirt-bin libvirt-dev seabios
  #- wget http://iso.reactos.org/regtestcd/bootcdregtest-70637.iso -O /tmp/bootcdregtest-70637.iso

language: c

compiler:
  - gcc

script:
  - svn checkout svn://svn.reactos.org/project-tools/trunk/sysreg2 /tmp/sysreg2
  - cd /tmp/sysreg2 && make
  - /tmp/sysreg2/sysreg2 ../sysreg.xml
  #- qemu-img create /tmp/ReactOS.img 2000M
  #- qemu-system-i386 -m 512 -cdrom /tmp/bootcdregtest-70637.iso -hda /tmp/ReactOS.img -boot d -localtime -serial stdio -vga std -vnc :0
