sudo: required
dist: trusty

env:
#  - export DISPLAY=:0
- MAKEFLAGS="-j3"
#- LIBVIRT_DEBUG=1

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  #- sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" >> /etc/apt/sources.list.d/virtualbox.list'
  #- wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update -qq
  #- sudo apt-get install -y linux-headers-3.13.0-63-generic qemu libvirt-bin libvirt-dev virtualbox-5.0
  #- sudo apt-get install -y linux-headers-3.19.0-30-generic qemu libvirt-bin libvirt-dev virtualbox-5.0
  #- sudo apt-get install -y linux-headers-3.19.0-30-generic virtualbox-4.3
  #- sudo apt-get install -y qemu-utils libvirt-bin libvirt-dev openssl
  - sudo apt-get install -y qemu-utils libvirt-dev
  #- sudo apt-get install -y qemu-kvm libvirt-bin libvirt-dev
  #- sudo apt-get install -q virtualbox --fix-missing

language: c

compiler:
  - gcc

script:
  #- sudo apt-get install -q linux-headers-3.13.0-63-generic
  #- sudo apt-get install -q virtualbox-5.0 --fix-missing
  #- sudo apt-get update -qq
  #- sudo apt-get source -qq -y -d libvirt
  #- sudo apt-get build-dep -qq -y libvirt > /dev/null
  #- dpkg-source -x libvirt*dsc
  #- cd libvirt-1.2.2
  - wget http://libvirt.org/sources/libvirt-1.3.1.tar.gz -O /tmp/libvirt-1.3.1.tar.gz
  - cd /tmp
  - tar -xzf /tmp/libvirt-1.3.1.tar.gz -C /tmp/
  - sudo apt-get install -qq -y libxml2-dev libgnutls-dev libdevmapper-dev libcurl4-gnutls-dev libpciaccess-dev libnl-dev uuid-dev
  - cd /tmp/libvirt-1.3.1
  #- ./configure --prefix=/usr --with-vbox --with-esx --disable-dependency-tracking --enable-expensive-tests=no --disable-expensive-tests --with-test-suite=no --without-test-suite --enable-silent-rules --disable-nls
  - ./configure --prefix=/usr --with-vbox --enable-silent-rules --disable-nls --disable-dependency-tracking
  - make -j 3
  - sudo make install
  - sudo ldconfig
  - sudo virsh net-list
  #- sudo service libvirtd restart
  #- sudo /etc/init.d/libvirt restart
  - /usr/sbin libvirtd -d
  #- sudo ./configure --help
  #- ./autogen.sh --system
  #- sudo make -j 2
  #- sudo make distclean > /dev/null
  #- sudo make -j 2 install
  #- sudo ldconfig
  #- sudo /etc/init.d/libvirt restart
  #- sudo service libvirt-bin start
  #- dpkg-buildpackage -us -uc -b -rfakeroot > /dev/null
  #- cd ..
  #- sudo dpkg -i libvirt-bin_1.2.2-0ubuntu13.1.16_amd64.deb libvirt0_1.2.2-0ubuntu13.1.16_amd64.deb
  - virsh -V
  - qemu-img create -f vmdk /tmp/ros.vmdk 2000M
  #- sudo apt-get install -y expect
  - wget https://download3.vmware.com/software/player/file/VMware-Player-6.0.6-2700073.x86_64.bundle -O /tmp/VMware.bundle
  - wget https://download3.vmware.com/software/player/file/VMware-VIX-1.13.6-2700073.x86_64.bundle -O /tmp/VMware-VIX.bundle
  - chmod +x /tmp/VMware.bundle
  - chmod +x /tmp/VMware-VIX.bundle
  - sudo /tmp/VMware.bundle --eulas-agreed --console --required
  - sudo /tmp/VMware-VIX.bundle --eulas-agreed --console --required
  #- sudo /usr/bin/vmplayer -v
  - git clone --depth=50 --branch=master https://github.com/AmineKhaldi/TestingTravis.git /tmp/TestingTravis
  #- chmod +x /tmp/TestingTravis/vbox.sh
  #- sudo /tmp/TestingTravis/vbox.sh
  - sudo /usr/bin/vmplayer -v
  - sudo virsh define /tmp/TestingTravis/reactos.xml
  - exit
  #- sudo virsh start ReactOS
  #- sudo VirtualBox & sleep 10s
  #- sudo virsh -c vbox:///system
  #- sudo virsh -c vbox:///session
  #- chmod +x ./vmware.sh
  #- sudo ./vmware.sh
  #- sudo vmware-modconfig --console --install-all
  - wget http://iso.reactos.org/regtestcd/bootcdregtest-70637.iso -O /tmp/bootcdregtest-70637.iso
  - svn checkout svn://svn.reactos.org/project-tools/trunk/sysreg2 /tmp/sysreg2
  - cd /tmp/sysreg2 && make
  - sudo /tmp/sysreg2/sysreg2 /tmp/TestingTravis/sysreg.xml
  #- /usr/bin/vmrun -T player list
  #- cd /tmp && ls
