sudo: required

before_script:
  #- sudo apt-get update -qq
  #- sudo apt-get install -y qemu-kvm libvirt-bin libvirt-dev
  #- sudo apt-get install -q virtualbox --fix-missing

language: c

compiler:
  - gcc

script:
  - sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" >> /etc/apt/sources.list.d/virtualbox.list'
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install virtualbox-5.0
  - git clone --depth=50 --branch=master https://github.com/AmineKhaldi/TestingTravis.git /tmp/TestingTravis
  - chmod +x /tmp/TestingTravis/vbox.sh
  - /tmp/TestingTravis/vbox.sh
  #- wget http://iso.reactos.org/regtestcd/bootcdregtest-70637.iso -O /tmp/bootcdregtest-70637.iso
  #- svn checkout svn://svn.reactos.org/project-tools/trunk/sysreg2 /tmp/sysreg2
  #- cd /tmp/sysreg2 && make
  #- sudo /tmp/sysreg2/sysreg2 /tmp/TestingTravis/sysreg.xml
