sudo: required
dist: trusty

env:
- MAKEFLAGS="-j3"
#- LIBVIRT_DEBUG=1

before_script:
  #- sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" >> /etc/apt/sources.list.d/virtualbox.list'
  #- wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update -qq
  #- sudo apt-get install -y linux-headers-3.13.0-63-generic qemu libvirt-bin libvirt-dev virtualbox-5.0
  #- sudo apt-get install -y linux-headers-3.19.0-30-generic qemu libvirt-bin libvirt-dev virtualbox-5.0
  #- sudo apt-get install -y linux-headers-3.19.0-30-generic virtualbox-4.3
  #- sudo apt-get install -y qemu-utils libvirt-bin libvirt-dev
  #- sudo apt-get install -y qemu-utils libvirt-dev
  #- sudo apt-get install -y qemu-kvm libvirt-bin libvirt-dev
  #- sudo apt-get install -q virtualbox --fix-missing

language: c

compiler:
  - gcc

script:
  #- sudo apt-get install -q linux-headers-3.13.0-63-generic
  #- sudo apt-get install -q virtualbox-5.0 --fix-missing
  #- sudo apt-get update -qq
  #- sudo apt-get source -qq -y -d libvirt
  #- sudo apt-get build-dep -qq -y libvirt > /dev/null
  #- dpkg-source -x libvirt*dsc
  #- cd libvirt-1.2.2
  #- sudo ./configure --with-vbox --disable-dependency-tracking --enable-expensive-tests=no --disable-expensive-tests --with-test-suite=no --without-test-suite --enable-silent-rules --disable-nls
  #- sudo ./configure --help
  #- ./autogen.sh --system
  #- sudo make -j 2
  #- sudo make distclean > /dev/null
  #- sudo make -j 2 install
  #- sudo ldconfig
  #- sudo /etc/init.d/libvirt restart
  #- sudo service libvirt-bin start
  #- dpkg-buildpackage -us -uc -b -rfakeroot > /dev/null
  #- cd ..
  #- ls
  #- exit
  #- sudo dpkg -i libvirt-bin_1.2.2-0ubuntu13.1.16_amd64.deb libvirt0_1.2.2-0ubuntu13.1.16_amd64.deb
  #- qemu-img create -f vdi /tmp/ros.img 2000M
  - sudo apt-get install -y expect
  - wget https://download3.vmware.com/software/player/file/VMware-Player-6.0.2-1744117.x86_64.bundle -O /tmp/VMware.bundle
  - git clone --depth=50 --branch=master https://github.com/AmineKhaldi/TestingTravis.git /tmp/TestingTravis
  - chmod +x /tmp/TestingTravis/vbox.sh
  - sudo /tmp/TestingTravis/vbox.sh
  #- sudo virsh define /tmp/TestingTravis/reactos.xml
  #- sudo virsh start ReactOS
  #- virsh -V
  #- exit
  #- sudo VirtualBox & sleep 10s
  #- sudo virsh -c vbox:///system
  #- sudo virsh -c vbox:///session
  #- chmod +x ./vmware.sh
  #- sudo ./vmware.sh
  - sudo vmware-modconfig --console --install-all
  - exit
  - wget http://iso.reactos.org/regtestcd/bootcdregtest-70637.iso -O /tmp/bootcdregtest-70637.iso
  - svn checkout svn://svn.reactos.org/project-tools/trunk/sysreg2 /tmp/sysreg2
  - cd /tmp/sysreg2 && make
  - sudo /tmp/sysreg2/sysreg2 /tmp/TestingTravis/sysreg.xml
