sudo: required
dist: trusty

before_script:
  - sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" >> /etc/apt/sources.list.d/virtualbox.list'
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update -qq
  #- sudo apt-get install -y linux-headers-3.13.0-63-generic qemu libvirt-bin libvirt-dev virtualbox-5.0
  - sudo apt-get install -y linux-headers-3.19.0-30-generic qemu libvirt-bin libvirt-dev virtualbox-5.0
  #- sudo apt-get install -y qemu-kvm libvirt-bin libvirt-dev
  #- sudo apt-get install -q virtualbox --fix-missing

language: c

compiler:
  - gcc

script:
  #- sudo apt-get install -q linux-headers-3.13.0-63-generic
  #- sudo apt-get install -q virtualbox-5.0 --fix-missing
  - qemu-img create /tmp/ros.img 2000M
  - git clone --depth=50 --branch=master https://github.com/AmineKhaldi/TestingTravis.git /tmp/TestingTravis
  - chmod +x /tmp/TestingTravis/vbox.sh
  - /tmp/TestingTravis/vbox.sh
  #- virsh -V
  - sudo xvfb-run -a /usr/bin/VirtualBox & sudo virsh -c vbox:///session
  - wget http://iso.reactos.org/regtestcd/bootcdregtest-70637.iso -O /tmp/bootcdregtest-70637.iso
  - svn checkout svn://svn.reactos.org/project-tools/trunk/sysreg2 /tmp/sysreg2
  - cd /tmp/sysreg2 && make
  - sudo /tmp/sysreg2/sysreg2 /tmp/TestingTravis/sysreg.xml
